import React, { useState } from 'react';
import Navbar from './components/Navbar';
import ResultCard from './components/ResultCard';
import EducationModule from './components/EducationModule';
import Button from './components/Button';
import { AppState, AnalysisResult, ScanConfig } from './types';
import { analyzeHemoImage } from './services/geminiService';
import { HeartIcon, BookOpenIcon, ChevronLeftIcon } from './icons';

// Import Views
import DisclaimerView from './components/views/DisclaimerView';
import HomeView from './components/views/HomeView';
import ScanView from './components/views/ScanView';

const App: React.FC = () => {
  const [state, setState] = useState<AppState>(AppState.DISCLAIMER);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [scanArea, setScanArea] = useState<ScanConfig['area']>('NailBed');
  const [capturedImage, setCapturedImage] = useState<string | null>(null);

  const handleImageSelected = async (base64: string) => {
    setCapturedImage(`data:image/jpeg;base64,${base64}`);
    setState(AppState.ANALYZING);
    
    const analysis = await analyzeHemoImage(base64, { area: scanArea });
    setResult(analysis);
    setState(AppState.RESULTS);
  };

  const resetApp = () => {
    setResult(null);
    setCapturedImage(null);
    setState(AppState.HOME);
  };

  const renderContent = () => {
    switch (state) {
      case AppState.DISCLAIMER:
        return <DisclaimerView onAcknowledge={() => setState(AppState.HOME)} />;

      case AppState.HOME:
        return <HomeView onNavigate={setState} />;

      case AppState.SCAN:
        return (
          <ScanView 
            scanArea={scanArea}
            setScanArea={setScanArea}
            onImageSelected={handleImageSelected}
            onBack={() => setState(AppState.HOME)}
          />
        );

      case AppState.ANALYZING:
        return (
          <div className="min-h-[80vh] flex flex-col justify-center items-center text-center px-8 animate-fade-in bg-white/50">
             <div className="relative mb-16">
               <div className="w-40 h-40 border-4 border-rose-100 border-t-rose-600 rounded-full animate-spin"></div>
               <div className="absolute inset-0 flex items-center justify-center">
                 <div className="relative">
                    <div className="absolute inset-0 bg-rose-500 blur-xl opacity-20 animate-pulse"></div>
                    <HeartIcon className="w-16 h-16 text-rose-600 relative z-10" />
                 </div>
               </div>
             </div>
             <h2 className="text-4xl font-bold text-slate-900 mb-4 tracking-tight">Analyzing Clinical Biomarkers</h2>
             <div className="max-w-xl mx-auto space-y-2 text-slate-500 text-lg">
                <p>Detecting Pallor Levels...</p>
                <p>Evaluating Hemoglobin Color Intensity...</p>
                <p>Checking Vascularization...</p>
             </div>
          </div>
        );

      case AppState.RESULTS:
        return result ? (
          <div className="px-6 py-12 max-w-7xl mx-auto animate-fade-in">
             <div className="mb-8 flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <button onClick={resetApp} className="p-2 hover:bg-white hover:shadow-md rounded-full transition-all border border-transparent hover:border-slate-100">
                    <ChevronLeftIcon className="w-6 h-6 text-slate-600" />
                  </button>
                  <div>
                      <h2 className="text-3xl font-bold text-slate-900">Analysis Report</h2>
                      <p className="text-slate-500">Generated by AI Model • {new Date().toLocaleDateString()}</p>
                  </div>
                </div>
                <Button variant="outline" onClick={resetApp}>Start New Scan</Button>
             </div>
             
             <div className="grid lg:grid-cols-12 gap-8 h-full">
                {/* Left Column: Image */}
                <div className="lg:col-span-4 space-y-6">
                    <div className="bg-white p-4 rounded-[2rem] shadow-lg border border-slate-100 h-fit sticky top-24">
                        <div className="aspect-square w-full rounded-[1.5rem] overflow-hidden bg-slate-100 relative">
                            {capturedImage && (
                                <img src={capturedImage} alt="Analyzed Subject" className="w-full h-full object-cover" />
                            )}
                            <div className="absolute bottom-4 right-4 bg-black/60 backdrop-blur-md text-white px-3 py-1 rounded-full text-sm font-medium">
                                {scanArea === 'NailBed' ? 'Fingernails' : 'Conjunctiva'}
                            </div>
                        </div>
                        <div className="mt-6 px-2">
                          <h4 className="font-bold text-slate-800 mb-3">Scan Metadata</h4>
                          <div className="space-y-3 text-sm text-slate-600">
                              <div className="flex justify-between pb-2 border-b border-slate-200">
                                  <span>Model Version</span>
                                  <span className="font-medium">Gemini 2.5 Flash</span>
                              </div>
                              <div className="flex justify-between pb-2 border-b border-slate-200">
                                  <span>Processing Time</span>
                                  <span className="font-medium">~1.2s</span>
                              </div>
                              <div className="flex justify-between">
                                  <span>Session ID</span>
                                  <span className="font-medium font-mono">#{Math.floor(Math.random() * 10000)}</span>
                              </div>
                          </div>
                        </div>
                    </div>
                </div>

                {/* Right Column: Results */}
                <div className="lg:col-span-8">
                   <ResultCard result={result} onRetry={resetApp} />
                </div>
             </div>
          </div>
        ) : null;

      case AppState.EDUCATION:
        return (
          <div className="px-6 py-12 max-w-7xl mx-auto">
            <div className="mb-10 text-center max-w-3xl mx-auto">
               <div className="inline-block p-3 bg-emerald-100 rounded-full mb-4">
                 <BookOpenIcon className="w-8 h-8 text-emerald-600" />
               </div>
               <h2 className="text-4xl md:text-5xl font-bold text-slate-900 mb-4 tracking-tight">Health & Nutrition Hub</h2>
               <p className="text-xl text-slate-600">Empowering you with knowledge to prevent and manage anemia effectively.</p>
            </div>
            <EducationModule />
          </div>
        );
    }
  };

  return (
    <div className="min-h-screen bg-slate-50/50 font-sans text-slate-900 selection:bg-rose-100">
      <Navbar 
        currentState={state} 
        onBack={() => setState(AppState.HOME)} 
      />
      <main className="w-full pb-20">
        {renderContent()}
      </main>
    </div>
  );
};

export default App;